name: 'Clang-Tidy'
description: 'Run diff-aware clang-tidy analysis inside a Docker container'

inputs:
  docker_image:
    description: 'Docker image with clang-tidy and compile_commands.json'
    required: true
  compile_commands_path:
    description: 'Path to directory containing compile_commands.json (inside container)'
    default: 'build'
  source_mount:
    description: 'Where repo source is mounted inside the container'
    default: '/workspace/src'
  source_setup:
    description: 'Shell command to source before running tools'
    default: ''
  clang_tidy_config:
    description: 'Path to .clang-tidy config'
    default: ''
  clang_tidy_jobs:
    description: 'Parallel clang-tidy jobs'
    default: '4'
  file_extensions:
    description: 'Space-separated C++ file extensions'
    default: 'cpp hpp h cc cxx'
  base_ref:
    description: 'Base branch for diff comparison'
    default: ''
  exclude_file:
    description: 'Path to file listing excluded paths'
    default: ''
  path:
    description: 'Subdirectory to scope file detection to'
    default: '.'
  max_annotations:
    description: 'Maximum number of annotations to emit'
    default: '50'
  pre_analysis_script:
    description: 'Script path (in repo) to run inside Docker before analysis'
    default: ''

outputs:
  warnings:
    description: 'Number of warnings found'
    value: ${{ steps.tidy.outputs.warnings }}
  errors:
    description: 'Number of errors found'
    value: ${{ steps.tidy.outputs.errors }}

runs:
  using: composite
  steps:
    - id: files
      uses: PavelGuzenfeld/standard/actions/diff-files@main
      with:
        file_extensions: ${{ inputs.file_extensions }}
        base_ref: ${{ inputs.base_ref }}
        exclude_file: ${{ inputs.exclude_file }}
        path: ${{ inputs.path }}

    - id: pre
      if: steps.files.outputs.count != '0' && inputs.pre_analysis_script != ''
      shell: bash
      run: |
        MOUNT="${{ inputs.source_mount }}"
        docker run --rm \
          -v "${{ github.workspace }}:${MOUNT}" \
          -w "${MOUNT}" \
          "${{ inputs.docker_image }}" \
          bash -c "${{ inputs.pre_analysis_script }}"

    - id: tidy
      if: steps.files.outputs.count != '0'
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.files.outputs.files }}
      run: |
        echo "$CHANGED_FILES" > "${{ github.workspace }}/changed_cpp_files.txt"

        SETUP_CMD=""
        if [ -n "${{ inputs.source_setup }}" ]; then
          SETUP_CMD="${{ inputs.source_setup }} && "
        fi

        CONFIG_ARG=""
        if [ -n "${{ inputs.clang_tidy_config }}" ]; then
          CONFIG_ARG="--config-file=${{ inputs.clang_tidy_config }}"
        fi

        JOBS="${{ inputs.clang_tidy_jobs }}"
        MOUNT="${{ inputs.source_mount }}"
        MAX_ANN="${{ inputs.max_annotations }}"
        OUTPUT_FILE="${{ runner.temp }}/clang_tidy_output.txt"

        docker run --rm \
          -v "${{ github.workspace }}:${MOUNT}" \
          -w "${MOUNT}" \
          "${{ inputs.docker_image }}" \
          bash -c "${SETUP_CMD}cat changed_cpp_files.txt | xargs -P${JOBS} -I{} clang-tidy -p ${{ inputs.compile_commands_path }} ${CONFIG_ARG} {} 2>&1" \
          > "${OUTPUT_FILE}" 2>&1 || true

        # Parse findings
        WARNS=$(grep -cE '^.+:[0-9]+:[0-9]+: warning:' "${OUTPUT_FILE}" || echo 0)
        ERRS=$(grep -E '^.+:[0-9]+:[0-9]+: error:' "${OUTPUT_FILE}" | grep -cv 'clang-diagnostic-' || echo 0)

        # Emit annotations
        grep -E '^.+:[0-9]+:[0-9]+: (warning|error):' "${OUTPUT_FILE}" | head -"${MAX_ANN}" | while IFS= read -r line; do
          ann_file=$(echo "$line" | cut -d: -f1)
          ann_line=$(echo "$line" | cut -d: -f2)
          ann_col=$(echo "$line" | cut -d: -f3)
          severity=$(echo "$line" | cut -d: -f4 | tr -d ' ')
          message=$(echo "$line" | cut -d: -f5-)
          echo "::${severity} file=${ann_file},line=${ann_line},col=${ann_col}::${message}"
        done

        echo "warnings=$WARNS" >> $GITHUB_OUTPUT
        echo "errors=$ERRS" >> $GITHUB_OUTPUT

        echo "clang-tidy: $WARNS warning(s), $ERRS error(s)"
        [ "$ERRS" -gt 0 ] && exit 1 || true

    - if: steps.files.outputs.count == '0'
      shell: bash
      run: echo "No changed C++ files — skipping clang-tidy"
