name: 'Ruff Check'
description: 'Run diff-aware Python linting with ruff via diff-quality'

inputs:
  python_version:
    description: 'Python version to use'
    default: '3.12'
  source_dirs:
    description: 'Space-separated source directories'
    default: 'src'
  base_ref:
    description: 'Base branch for diff comparison'
    default: ''
  fail_under:
    description: 'Minimum diff-quality score (0-100)'
    default: '100'
  ruff_version:
    description: 'Ruff version to install (empty for latest)'
    default: ''
  diff_cover_version:
    description: 'diff-cover version to install (empty for latest)'
    default: ''
  ruff_select:
    description: 'Comma-separated ruff rule selectors (e.g. E,F,W,I)'
    default: ''
  ruff_ignore:
    description: 'Comma-separated ruff rules to ignore'
    default: ''
  line_length:
    description: 'Maximum line length for ruff'
    default: ''
  target_python:
    description: 'Target Python version for ruff (e.g. py312)'
    default: ''

outputs:
  passed:
    description: 'Whether the check passed'
    value: ${{ steps.lint.outputs.passed }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - shell: bash
      run: |
        RUFF_PKG="ruff"
        if [ -n "${{ inputs.ruff_version }}" ]; then
          RUFF_PKG="ruff==${{ inputs.ruff_version }}"
        fi
        DIFF_PKG="diff-cover"
        if [ -n "${{ inputs.diff_cover_version }}" ]; then
          DIFF_PKG="diff-cover==${{ inputs.diff_cover_version }}"
        fi
        pip install "$RUFF_PKG" "$DIFF_PKG"

    - id: lint
      shell: bash
      run: |
        BASE="${{ inputs.base_ref || github.base_ref || 'main' }}"

        RUFF_ARGS=""
        if [ -n "${{ inputs.ruff_select }}" ]; then
          RUFF_ARGS="$RUFF_ARGS --select=${{ inputs.ruff_select }}"
        fi
        if [ -n "${{ inputs.ruff_ignore }}" ]; then
          RUFF_ARGS="$RUFF_ARGS --ignore=${{ inputs.ruff_ignore }}"
        fi
        if [ -n "${{ inputs.line_length }}" ]; then
          RUFF_ARGS="$RUFF_ARGS --line-length=${{ inputs.line_length }}"
        fi
        if [ -n "${{ inputs.target_python }}" ]; then
          RUFF_ARGS="$RUFF_ARGS --target-version=${{ inputs.target_python }}"
        fi

        # Run ruff on source dirs to generate output
        ruff check ${{ inputs.source_dirs }} ${RUFF_ARGS} --output-format=pylint > "${{ runner.temp }}/ruff_output.txt" 2>&1 || true

        # Run diff-quality
        if diff-quality --violations=ruff.check \
          --compare-branch="origin/${BASE}" \
          --fail-under=${{ inputs.fail_under }}; then
          echo "passed=true" >> $GITHUB_OUTPUT
          echo "ruff: diff-quality passed"
        else
          echo "passed=false" >> $GITHUB_OUTPUT
          echo "ruff: diff-quality failed"
          exit 1
        fi
